steps:
  - label: ":linux: :julia: Run tests on v1.6"
    plugins:
      - JuliaCI/julia#v1:
          version: '1.6'
      - JuliaCI/julia-test#v1:
    agents:
      queue: "juliaecosystem"
      os: "linux"

  - label: ":linux: :julia: Run tests on v1"
    plugins:
      - JuliaCI/julia#v1:
          version: '1'
      - JuliaCI/julia-test#v1:
    agents:
      queue: "juliaecosystem"
      os: "linux"