steps:
  - label: ":linux: :julia: Run tests on v1.8"
    plugins:
      - JuliaCI/julia#v1:
          version: '1.8'
      - JuliaCI/julia-test#v1:
    agents:
      queue: "juliaecosystem"
      os: "linux"
      arch: "x86_64"

  - label: ":linux: :julia: Run tests on v1"
    plugins:
      - JuliaCI/julia#v1:
          version: '1'
      - JuliaCI/julia-test#v1:
    agents:
      queue: "juliaecosystem"
      os: "linux"
      arch: "x86_64"

  - label: ":macos: :julia: Run tests on v1"
    plugins:
      - JuliaCI/julia#v1:
          version: '1'
      - JuliaCI/julia-test#v1:
    agents:
      queue: "juliaecosystem"
      os: "macos"
      arch: "x86_64"

  - label: ":linux: :julia: Run tests on nightly"
    plugins:
      - JuliaCI/julia#v1:
          version: 'nightly'
      - JuliaCI/julia-test#v1:
    agents:
      queue: "juliaecosystem"
      os: "linux"
      arch: "x86_64"
    soft_fail: "true"
